/*
 * File: app/controller/ClientDetailController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.controller.ClientDetailController', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.app.Route'
    ],

    config: {
        routes: {
            'private/pacients/:contactId/:pacientId/:name': 'main'
        },

        refs: {
            clientDetailView: {
                autoCreate: true,
                selector: 'clientDetailView',
                xtype: 'clientDetailView'
            },
            mainContainer: 'mainContainer',
            clientDetailTitle: 'clientDetailView toolbar',
            quickInfo: 'clientDetailView #quickInfo',
            nurseCareInfo: 'clientDetailView #clientInfoContainer #nurseCareInfo',
            menu: 'clientDetailView #menu',
            drugList: 'clientDetailView #drugContainer list',
            nurseCareList: 'clientDetailView #clientInfoContainer list',
            doctorCareList: '#doctorContainer list',
            consultationCareList: '#consultationContainer list',
            doctorCareInfo: '#doctorContainer #doctorCareInfo',
            consultationCareInfo: '#consultationContainer #consultationCareInfo'
        },

        control: {
            "clientDetailView #clientInfoContainer list": {
                select: 'onCareListItemTap'
            },
            "clientDetailView #doctorContainer list": {
                select: 'onDoctorListItemTap'
            },
            "clientDetailView #consultationContainer list": {
                select: 'onConsultantListItemTap'
            },
            "clientDetailView #menu button": {
                tap: 'onMenuButton'
            },
            "clientDetailView #newRecord": {
                tap: 'onNewRecord'
            },
            "clientDetailView #back": {
                tap: 'onBack'
            }
        }
    },

    onCareListItemTap: function(dataview, record, eOpts) {
        this.getNurseCareInfo().setHtml(this.nurseCareTemplate.apply(record.getData()));
    },

    onDoctorListItemTap: function(dataview, record, eOpts) {
        this.getDoctorCareInfo().setHtml(this.doctorCareTemplate.apply(record.getData()));
    },

    onConsultantListItemTap: function(dataview, record, eOpts) {
        this.getConsultationCareInfo().setHtml(this.consultantCareTemplate.apply(record.getData()));
    },

    onMenuButton: function(button, e, eOpts) {
        //Ext.Msg.alert('test');
        switch (button.getItemId()) {
            case 'nurse':
                this.getClientDetailView().setActiveItem(0);
                break;
            case 'drug':
                this.getClientDetailView().setActiveItem(1);
                break;
            case 'doctor':
                this.getClientDetailView().setActiveItem(2);
                break;
            case 'consultation':
                this.getClientDetailView().setActiveItem(3);
                break;
        }
    },

    onNewRecord: function(button, e, eOpts) {
        this.getApplication().fireEvent("newNurseCareRequested", this.pacient.get('ID'));
    },

    onBack: function(button, e, eOpts) {
        this.getApplication().fireEvent("clientsView");
    },

    main: function(contactId, pacientId, name) {
        this.getApplication().fireEvent("loginRequested", this, function () {
            var messageBox = Ext.Msg.show({
                title: "Načítám data...",
                buttons: []
            });

            this.getClientDetailView();// inicializace pomocí autocreate
            this.getMenu().setPressedButtons([0]);

            var Pacient = Ext.ModelManager.getModel('CestaDomu.model.Pacient');

            Pacient.load(pacientId, {
                scope: this,
                success: function(pacient) {
                    if (pacient === null) {
                        pacient = new Pacient();
                        pacient.set("ID", contactId);
                        pacient.set("Name", decodeURIComponent(name));
                    }
                    this.pacient = pacient;
                    this.getClientDetailView().setActiveItem(0);
                    var nurseCareStore = this.getNurseCareList().getStore();
                    nurseCareStore.filter('id', pacient.get('ID'));
                    nurseCareStore.load(function(records, operation, success) {
                        if (success && records[0]) {
                            this.getNurseCareList().select(records[0], false, false);
                        }
                    }, this);

                    var drugStore = this.getDrugList().getStore();
                    drugStore.filter('id', pacient.get('ID'));
                    drugStore.load();


                    var doctorCareStore = this.getDoctorCareList().getStore();
                    doctorCareStore.filter('id', pacient.get('ID'));
                    doctorCareStore.load(function(records, operation, success) {
                        if (success && records[0]) {
                            this.getDoctorCareList().select(records[0], false, false);
                        }
                    }, this);

                    var consultationCareStore = this.getConsultationCareList().getStore();
                    consultationCareStore.filter('id', pacient.get('ID'));
                    consultationCareStore.load(function(records, operation, success) {
                        if (success && records[0]) {
                            this.getConsultationCareList().select(records[0], false, false);
                        }
                    }, this);

                    this.getQuickInfo().setHtml(this.quickInfoTemplate.apply(pacient.getData()));
                    this.getMainContainer().setActiveItem(this.getClientDetailView());
                    messageBox.hide();
                },
                failure: function () {
                    Ext.Msg.alert('Chyba', 'Nepodařilo se načíst data klienta.');
                }
            });
        });
    },

    onPacientSelected: function(contactId, pacientId, name) {
        this.getApplication().redirectTo("private/pacients/"+contactId+"/"+pacientId+"/"+encodeURIComponent(name));
    },

    constructor: function() {
        this.callParent(arguments);
        this.quickInfoTemplate = new Ext.XTemplate(
            '{Name} <tpl if="contactPerson">, <a href="http://mapy.cz/?q={street}, {city}" style="color: #99CCFF; text-decoration: none;" target="_blank">{street}, {city}</a></tpl><br/>',
            '<tpl if="contactPerson">Pečující: {contactPerson}<tpl if="mobileNumber">, {mobilePrefix} {mobileNumber}</tpl><tpl if="phoneNumber">, {phonePrefix} {phoneNumber}</tpl></tpl><tpl if="!contactPerson">Pečující osoba není zadána</tpl>'
        );

        this.nurseCareTemplate = new Ext.XTemplate(
            'Délka: {durationtime} min.<br/>',
            'Popis: {Description}'
        );

        this.doctorCareTemplate = new Ext.XTemplate(
            'Délka: {durationtime} min.<br/>',
            'Číslo zprávy: {medicalReportNr}<br/>',
            'Epikríza: {Epikriza}'
        );

        this.consultantCareTemplate = new Ext.XTemplate(
            'Délka: {durationtime} min.<br/> ',
            'Reflexe: {jakToVidim} <br/>',
            'Popis: {Description}'
        );
    },

    init: function(application) {

        application.on([
        { event: 'pacientSelected', fn: this.onPacientSelected, scope: this }
        ]);
    }

});