/*
 * File: app/controller/ClientDetailController.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.controller.ClientDetailController', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.app.Route'
    ],

    config: {
        routes: {
            'private/pacients/:pacientId': 'main'
        },

        refs: {
            clientDetailView: {
                autoCreate: true,
                selector: 'clientDetailView',
                xtype: 'clientDetailView'
            },
            loadingView: {
                autoCreate: true,
                selector: 'loadingView',
                xtype: 'loadingView'
            },
            mainContainer: 'mainContainer',
            clientNewMenu: {
                autoCreate: true,
                selector: 'clientNewMenu',
                xtype: 'clientNewMenu'
            },
            clientDetailTitle: 'clientDetailView toolbar',
            clientInfoContainer: 'clientDetailView #clientInfoContainer',
            caruselTitle: 'clientDetailView #caruselTitle',
            quickInfo: 'clientDetailView #quickInfo',
            nurseCareLength: 'clientDetailView #nurseCareLength',
            nurseCareDescription: 'clientDetailView #nurseCareDescription'
        },

        control: {
            "clientDetailView carousel": {
                activeitemchange: 'onCarouselActiveItemChange'
            },
            "clientDetailView button": {
                tap: 'onShowNewItemMenu'
            },
            "clientDetailView #clientInfoContainer list": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onCarouselActiveItemChange: function(container, value, oldValue, eOpts) {
        this.getCaruselTitle().setHtml(value.title);
    },

    onShowNewItemMenu: function(button, e, eOpts) {

    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        this.getNurseCareLength().setHtml(record.get('length'));
        this.getNurseCareDescription().setHtml(record.get('description'));
    },

    main: function(pacientId) {
        CestaDomu.controller.Login.doLogged(this, function () {
            var messageBox = Ext.Msg.show({
                title: "Načítám data...",
                buttons: []
            });

            var Pacient = Ext.ModelManager.getModel('CestaDomu.model.Pacient');

            Pacient.load(pacientId, {
                scope: this,
                success: function(pacient) {
                    var nurseCareStore = Ext.getStore('NurseCareStore');
                    nurseCareStore.filter('id', pacient.get('ID'));
                    nurseCareStore.load();

                    this.getMainContainer().setActiveItem(this.getClientDetailView());
                    this.getQuickInfo().setHtml(this.quickInfoTemplate.apply(pacient.getData()));
                    // ruční volání handleru události změny v caruselu pro nastavení nadpisu obrazovky
                    // jsou uvedeny pouze parametry, které se ve funkci používají, přestože signatura je rozsáhlejší
                    this.onCarouselActiveItemChange(null, this.getClientInfoContainer());
                    messageBox.hide();
                },
                failure: function () {
                    Ext.Msg.alert('Chyba', 'Nepodařilo se načíst data klienta.');
                }
            });
        });
    },

    onPacientSelected: function(pacientId) {
        this.getApplication().redirectTo("private/pacients/"+pacientId);
    },

    constructor: function() {
        this.callParent(arguments);
        this.quickInfoTemplate = new Ext.XTemplate(
            '{Name}, <a href="http://mapy.cz/?q={street}, {city}" style="color: #99CCFF; text-decoration: none;" target="_blank">{street}, {city}</a><br/>',
            'Ošetřuje: {contactPerson}<tpl if="mobileNumber">, {mobilePrefix} {mobileNumber}</tpl><tpl if="phoneNumber">, {phonePrefix} {phoneNumber}</tpl>'
        );
    },

    init: function(application) {

        application.on([
        { event: 'pacientSelected', fn: this.onPacientSelected, scope: this }
        ]);
    }

});