/*
 * File: app/controller/GetBindingViewX.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.controller.GetBindingViewX', {
    extend: 'Ext.Base',

    requires: [
        'CestaDomu.controller.Intuo',
        'Ext.XTemplate'
    ],
    singleton: true,

    config: {
    },

    constructor: function() {
        this.callParent(arguments);
        this.url = CestaDomu.controller.Intuo.commonServiceUrlPart;
        this.template = new Ext.XTemplate(
            '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:dig="http://digres.cz/">',
                '<soapenv:Header/>',
                '<soapenv:Body>',
                    '<dig:GetBindingViewX>',
                        '<dig:strAuthKey>{token}</dig:strAuthKey>',
                        '<dig:nViewID>{requestParams.viewId}</dig:nViewID>',
                        '<dig:nFromID>{filters.id}</dig:nFromID>',
                        '<dig:strLanguage>CS</dig:strLanguage>',
                        '<tpl if="filterXml"><dig:strXMLDefinitionOfRestriction><![CDATA[{filterXml}]]></dig:strXMLDefinitionOfRestriction></tpl>',
                    '</dig:GetBindingViewX>',
                '</soapenv:Body>',
            '</soapenv:Envelope>'
        );
    }

});