/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.controller.Login', {
    extend: 'Ext.Base',

    requires: [
        'Ext.XTemplate',
        'CestaDomu.controller.Intuo'
    ],
    singleton: true,

    config: {
    },

    constructor: function() {
        this.url = CestaDomu.controller.Intuo.commonServiceUrlPart;
        this.template = new Ext.XTemplate(
            '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:dig="http://digres.cz/">',
                '<soapenv:Header/>',
                '<soapenv:Body>',
                    '<dig:Login>',
                        '<dig:strLoginName>{username}</dig:strLoginName>',
                        '<dig:strPassword>{password}</dig:strPassword>',
                    '</dig:Login>',
                '</soapenv:Body>',
            '</soapenv:Envelope>'
        );
        this.callParent(arguments);
    }

});