/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.controller.Login', {
    extend: 'Ext.Base',

    requires: [
        'Ext.XTemplate',
        'CestaDomu.controller.Intuo'
    ],
    singleton: true,

    config: {
    },

    constructor: function() {
        this.callParent(arguments);
        this.url = CestaDomu.controller.Intuo.commonServiceUrlPart;
        this.safeDifference = 1000*60*7;
        this.maxDifference = 1000*60*9;
        this.failDifference = 1000*60*12;
        this.template = new Ext.XTemplate(
            '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:dig="http://digres.cz/">',
                '<soapenv:Header/>',
                '<soapenv:Body>',
                    '<dig:Login>',
                        '<dig:strLoginName>{username}</dig:strLoginName>',
                        '<dig:strPassword>{password}</dig:strPassword>',
                    '</dig:Login>',
                '</soapenv:Body>',
            '</soapenv:Envelope>'
        );
    },

    login: function(data, scope, success, failure) {
        if((typeof(Storage)==="undefined")) {
            Ext.Msg.alert('Nepodporovaný prohlížeč', 'Váš prohlížeč nepodporuje technologie (local storage) vyžadované touto aplikací, prosím použijte jiný prohlížeč.');
        } else {
            Ext.Ajax.request({
                url: this.url,
                method: 'POST',
                scope: this,
                xmlData: this.template.apply(data),
                success: function(response, options) {
                    var authTokenTag = Ext.DomQuery.selectNode("LoginResult", response.responseXML);
                    if (authTokenTag) {
                        var token = authTokenTag.textContent;
                        if (token) {
                            this.saveToken(token);
                            this.saveCredentials(data.username, data.password);
                            this.scheduleLoginRefresh();
                            Ext.callback(success, scope, [response, options]);
                            return;
                        }
                    }
                    this.scheduleLoginRefresh();
                    Ext.callback(failure, scope, [response, options]);
                },
                failure: function(response, options) {
                    this.scheduleLoginRefresh();
                    Ext.callback(failure, scope, [response, options]);
                }
            });
        }
    },

    loginRefresh: function() {
        var lastTokenTimeDifference = 0;
        if (this.getTokenTime()) {
            lastTokenTimeDifference = new Date().getTime() - this.getTokenTime();
        }

        this.login(
            this.getCredentials,
            this,
            function (response, options) {
                if (lastTokenTimeDifference > this.maxDifference) {
                    Ext.Msg.alert('Přihlášení obnoveno', 'Přihlášení k serveru bylo obnoveno.');
                }
            },
            function(response, options) {
                return;
            }
        );

    },

    scheduleLoginRefresh: function() {
        if (this.getCredentials()) {
            var tokenTime = this.getTokenTime();
            if (tokenTime) {
                var oneMinute = 1000*60;
                var now = new Date();
                var difference = now.getTime() - tokenTime;
                if (difference > this.failDifference) {
                    Ext.Msg.alert('Přihlášení vypršelo', 'Všechny pokusy o obnovu přihlášení selhaly, server je pravděpodobně trvale nedostupný.');
                    this.saveCredentials('', '');
                    this.setToken('');
                } else if (difference > this.maxDifference) {
                    Ext.Msg.alert('Přihlášení vypršelo', 'Další pokus o obnovu přihlášení proběhne za 1 min. Do té doby nebude aplikace funkční.');
                    Ext.defer(this.loginRefresh, oneMinute, this);
                } else if (difference > this.safeDifference) {
                    Ext.defer(this.loginRefresh, oneMinute, this);
                } else {
                    Ext.defer(this.loginRefresh, tokenTime + this.safeDifference - now.getTime(), this);
                }
            } else {
                this.loginRefresh();
            }
        }

    },

    isLoggedIn: function() {
        if (this.getToken() && this.getTokenTime()) {
            if (new Date().getTime() - this.getTokenTime() < this.maxDifference) {
                return true;
            }
        }

        return false;
    },

    getCredentials: function() {
        if((typeof(Storage) !== "undefined")) {
            if (sessionStorage.username) {
                return {
                    username: sessionStorage.username,
                    password: sessionStorage.password
                };
            }
        }

        return null;
    },

    saveCredentials: function(username, password) {
        if((typeof(Storage) !== "undefined")) {
            sessionStorage.username = username;
            sessionStorage.password = password;
        }
    },

    getTokenTime: function() {
        if((typeof(Storage) !== "undefined")) {
            if (sessionStorage.tokenTime) {
                return parseInt(sessionStorage.tokenTime, 10);
            }
        }

        return 0;
    },

    getToken: function() {
        if((typeof(Storage) !== "undefined")) {
            if (sessionStorage.token) {
                return sessionStorage.token;
            }
        }

        return '';
    },

    saveToken: function(token) {
        if((typeof(Storage) !== "undefined")) {
            sessionStorage.token = token;
            sessionStorage.tokenTime = new Date().getTime();
        }
    }

});