/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.controller.LoginController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.loginController',

    requires: [
        'Ext.app.Route',
        'Ext.MessageBox',
        'CestaDomu.controller.Login',
        'CestaDomu.controller.Intuo'
    ],

    config: {
        routes: {
            'public/login': 'main'
        },

        refs: {
            mainContainer: 'mainContainer',
            loginForm: 'loginView formpanel',
            loginView: {
                autoCreate: true,
                selector: 'loginView',
                xtype: 'loginView'
            },
            saveUsernameHelp: {
                autoCreate: true,
                selector: 'saveUsernameHelp',
                xtype: 'saveUsernameHelp'
            },
            username: 'loginView #username',
            saveUsername: 'loginView #saveUsername'
        },

        control: {
            "loginView #loginButton": {
                tap: 'onLogin'
            },
            "loginView #saveUsernameHelpButton": {
                tap: 'showHelp'
            },
            "loginView #saveUsername": {
                check: 'onSaveUsernameCheck',
                uncheck: 'onSaveUsernameUncheck'
            }
        }
    },

    onLogin: function(button, e, eOpts) {
        var messageBox = Ext.Msg.show({
            title: "Probíhá ověřování...",
            buttons: []
        });

        var values = this.getLoginForm().getValues();

        CestaDomu.controller.Login.login(
            values,
            this,
            function(response){
                messageBox.hide();
                if (this.getSaveUsername().isChecked() && (typeof(Storage) !== "undefined")) {
                    localStorage.savedUsername = values.username;
                }
                if (this.loginAction) {
                    var loginAction = this.loginAction;
                    this.loginAction = null;
                    Ext.callback(loginAction.loginSuccess, loginAction.loginCallbackScope);
                } else {
                    this.getApplication().fireEvent("loggedIn");
                }
            },function(response) {
                Ext.Msg.alert("Přihlášení se nezdařilo");
            });


    },

    showHelp: function(button, e, eOpts) {
        this.getSaveUsernameHelp().showBy(button);
    },

    onSaveUsernameCheck: function(checkboxfield, e, eOpts) {
        //Ext.Msg.alert("ahoj", "ahoj");
    },

    onSaveUsernameUncheck: function(checkboxfield, e, eOpts) {
        if((typeof(Storage) !== "undefined")) {
            localStorage.savedUsername = "";
        }
    },

    main: function() {
        this.getMainContainer().setActiveItem(this.getLoginView());

        if((typeof(Storage) !== "undefined")) {
            if (localStorage.savedUsername) {
                this.getSaveUsername().setChecked(true);
                this.getUsername().setValue(localStorage.savedUsername);
            }
        }
    },

    onHome: function() {
        this.getApplication().redirectTo("public/login");
    },

    onLoginRequested: function(scope, success) {
        if (CestaDomu.controller.Login.isLoginActive()) {
            Ext.callback(success, scope);
        } else if (CestaDomu.controller.Login.isLoggedIn()) {
            CestaDomu.controller.Login.refreshLogin(scope, success);
        } else {
            this.loginAction = {
                loginCallbackScope: scope,
                loginSuccess: success
            };
            this.getMainContainer().setActiveItem(this.getLoginView());
        }
    },

    init: function(application) {

        application.on([
        { event: 'home', fn: this.onHome, scope: this },
        { event: 'loginRequested', fn: this.onLoginRequested, scope: this }
        ]);
    }

});