/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    paths: {
        Ext: 'touch/src',
        Lib: 'lib',
        CestaDomu: 'app'
    }
});


Ext.application({

    requires: [
        'Ext.Loader'
    ],
    models: [
        'Contact',
        'Employee',
        'TimeInterval',
        'WorkReport',
        'TimeFund'
    ],
    stores: [
        'ContactsStore',
        'EmployeesStore',
        'WorkReportIntervals',
        'WorkReportsStore',
        'TimeFundStore'
    ],
    views: [
        'LoginView',
        'MainContainer',
        'ClientsView',
        'RoleSelectView',
        'LoadingView',
        'ClientDetailView',
        'ClientNewMenu',
        'WorkReportsView'
    ],
    requires: [
        'Lib.IntuoProxy',
        'Lib.IntuoWriter',
        'Lib.IntuoReader',
        'Ext.TitleBar',
        'Ext.form.Panel',
        'Ext.field.Password',
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.carousel.Carousel',
        'Ext.Label',
        'Ext.field.Select',
        'Ext.XTemplate',
        'CestaDomu.controller.Util'
    ],
    controllers: [
        'LoginController',
        'RoleSelectController',
        'DefaultController',
        'ClientsController',
        'ClientDetailController',
        'WorkReportsController'
    ],
    name: 'CestaDomu',

    launch: function() {

        Ext.create('CestaDomu.view.MainContainer', {fullscreen: true});
    }

});
