/*
 * File: app/model/Contact.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.model.Contact', {
    extend: 'Ext.data.Model',
    alias: 'model.contact',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Xml',
        'Ext.data.writer.Xml'
    ],

    config: {
        idProperty: 'ID',
        identifier: {
            type: 'simple'
        },
        fields: [
            {
                name: 'ID',
                type: 'auto'
            },
            {
                name: 'Name',
                type: 'string'
            },
            {
                name: 'pacientId',
                type: 'int'
            }
        ],
        proxy: {
            type: 'intuo',
            api: {
                read: {
                    service: CestaDomu.controller.GetObjectInfo
                }
            },
            url: 'xxx',
            reader: {
                type: 'intuo',
                rootProperty: 'GetObjectInfoResponse',
                record: 'GetObjectInfoResult'
            },
            writer: {
                type: 'intuo'
            }
        }
    }
});