/*
 * File: app/model/DoctorCare.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.model.DoctorCare', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'ID',
                type: 'auto'
            },
            {
                name: 'medicalReportNr',
                type: 'int'
            },
            {
                name: 'medicalReporttype',
                type: 'string'
            },
            {
                name: 'startDate',
                type: 'date'
            },
            {
                name: 'durationtime',
                type: 'int'
            },
            {
                name: 'Epikriza',
                type: 'string'
            },
            {
                name: 'doctor',
                type: 'string'
            }
        ]
    }
});