/*
 * File: app/model/Drug.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.model.Drug', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        idProperty: 'ID',
        fields: [
            {
                name: 'ID',
                type: 'auto'
            },
            {
                name: 'drugDate',
                type: 'date'
            },
            {
                name: 'sos',
                type: 'boolean'
            },
            {
                name: 'name',
                type: 'string'
            },
            {
                name: 'applicationType',
                type: 'string'
            },
            {
                name: 'dose',
                type: 'string'
            },
            {
                name: 'symptom',
                type: 'string'
            },
            {
                name: 'authorizedByDoctor',
                type: 'boolean'
            },
            {
                name: 'startDate',
                type: 'date'
            },
            {
                name: 'endDate',
                type: 'date'
            },
            {
                name: 'interval',
                type: 'string'
            },
            {
                name: 'maxDose',
                type: 'string'
            },
            {
                name: 'note',
                type: 'string'
            },
            {
                convert: function(v, rec) {
                    return Ext.Date.format(rec.get('drugDate'), 'Ymd') + (rec.get('sos') ? ' b' : 'a');
                },
                name: 'group',
                type: 'string'
            }
        ]
    }
});