/*
 * File: app/model/NurseCare.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.model.NurseCare', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        idProperty: 'ID',
        fields: [
            {
                name: 'ID',
                type: 'auto'
            },
            {
                name: 'time',
                type: 'date'
            },
            {
                name: 'nurse',
                type: 'string'
            },
            {
                name: 'aggreement',
                type: 'string'
            },
            {
                name: 'description',
                type: 'string'
            },
            {
                name: 'length',
                type: 'int'
            }
        ]
    }
});