/*
 * File: app/model/TimeNumber.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.model.TimeNumber', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id',
                type: 'auto'
            },
            {
                convert: function(v, rec) {
                    return rec.get('id');
                },
                name: 'value',
                type: 'int'
            },
            {
                convert: function(v, rec) {
                    var value = rec.get('value');
                    return (value < 10) ? ("0" + value) : value;
                },
                name: 'label',
                type: 'string'
            }
        ]
    }
});