/*
 * File: app/store/DrugStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.store.DrugStore', {
    extend: 'Ext.data.Store',

    requires: [
        'CestaDomu.model.Drug',
        'Ext.data.proxy.Ajax',
        'Ext.data.writer.Xml',
        'Ext.data.reader.Xml',
        'Ext.util.Grouper'
    ],

    config: {
        model: 'CestaDomu.model.Drug',
        remoteFilter: true,
        storeId: 'DrugStore',
        proxy: {
            type: 'intuo',
            api: {
                read: {
                    service: CestaDomu.controller.GetBindingViewX,
                    templates: {
                        
                    }
                },
                mappingType: 'xml',
                mapping: {
                    ID: 'c0',
                    drugDate: 'c1',
                    sos: 'c2',
                    name: 'c3',
                    applicationType: 'c4',
                    dose: 'c5',
                    symptom: 'c6',
                    authorizedByDoctor: 'c7',
                    startDate: 'c8',
                    endDate: 'c9',
                    interval: 'c10',
                    maxDose: 'c11',
                    note: 'c12'
                }
            },
            extraParams: {
                viewId: 1723
            },
            url: 'xxx',
            writer: {
                type: 'intuo'
            },
            reader: {
                type: 'intuo',
                rootProperty: 'DocumentElement',
                record: 'WEB_x0020_medikace'
            }
        },
        grouper: {
            groupFn: function(item) {
                return Ext.Date.format(item.get('drugDate'), 'd. m. Y H:i') + (item.get('sos') ? ' SOS' : '');
            },
            direction: 'DESC',
            sortProperty: 'group'
        }
    }
});