/*
 * File: app/store/EmployeesStore.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.store.EmployeesStore', {
    extend: 'Ext.data.Store',

    requires: [
        'CestaDomu.model.Employee',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Xml',
        'Ext.data.writer.Xml'
    ],

    config: {
        model: 'CestaDomu.model.Employee',
        storeId: 'EmployeesStore',
        proxy: {
            type: 'intuo',
            api: {
                read: {
                    service: CestaDomu.controller.GetViewX
                },
                mappingType: 'xml',
                mapping: {
                    Forename: 'c1',
                    Surname: 'c2',
                    Position: 'c3'
                }
            },
            extraParams: {
                viewId: 1707
            },
            url: 'xxx',
            reader: {
                type: 'intuo',
                rootProperty: 'DocumentElement',
                record: 'WEB_x0020_zaměstnanci_x0020_pro_x0020_výkaz_x0020_práce'
            },
            writer: {
                type: 'intuo'
            }
        }
    }
});