/*
 * File: app/store/Hours.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.store.Hours', {
    extend: 'Ext.data.Store',

    requires: [
        'CestaDomu.model.TimeNumber'
    ],

    config: {
        data: [
            {
                id: 0
            },
            {
                id: 1
            },
            {
                id: 2
            },
            {
                id: 3
            },
            {
                id: 4
            },
            {
                id: 5
            },
            {
                id: 6
            },
            {
                id: 7
            },
            {
                id: 8
            },
            {
                id: 9
            },
            {
                id: 10
            },
            {
                id: 11
            },
            {
                id: 12
            },
            {
                id: 13
            },
            {
                id: 14
            },
            {
                id: 15
            },
            {
                id: 16
            },
            {
                id: 17
            },
            {
                id: 18
            },
            {
                id: 19
            },
            {
                id: 20
            },
            {
                id: 21
            },
            {
                id: 22
            },
            {
                id: 23
            }
        ],
        model: 'CestaDomu.model.TimeNumber',
        storeId: 'Hours'
    }
});