/*
 * File: app/store/TimeFundStore.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.store.TimeFundStore', {
    extend: 'Ext.data.Store',

    requires: [
        'CestaDomu.model.TimeFund',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Xml',
        'Ext.data.writer.Xml'
    ],

    config: {
        model: 'CestaDomu.model.TimeFund',
        remoteFilter: true,
        remoteGroup: true,
        remoteSort: true,
        storeId: 'TimeFundStore',
        proxy: {
            type: 'intuo',
            api: {
                read: {
                    service: CestaDomu.controller.GetBindingViewX,
                    templates: {
                        filterXml: new Ext.XTemplate('<Element type="LogicalOperator"><SubElements><ElementCollection><Item><Element type="Parenthesis"><SubElements><ElementCollection><Item><Element type="Comparison"><SubElements><ElementCollection><Item><Element type="ColumnName"><AdditionalData columnName="To.(timeFund).yearTF" displayName="Konec vazby.Časový fond.Rok" type="2" /></Element></Item><Item><Element type="Constant"><AdditionalData><anyType xmlns:q1="http://www.w3.org/2001/XMLSchema" d15p1:type="q1:double" xmlns:d15p1="http://www.w3.org/2001/XMLSchema-instance">{filters.year}</anyType></AdditionalData></Element></Item></ElementCollection></SubElements><AdditionalData Operator="Equal" /></Element></Item></ElementCollection></SubElements><AdditionalData /></Element></Item><Item><Element type="Parenthesis"><SubElements><ElementCollection><Item><Element type="Comparison"><SubElements><ElementCollection><Item><Element type="ColumnName"><AdditionalData columnName="To.(timeFund).monthTF" displayName="Konec vazby.Časový fond.Měsíc" type="2" /></Element></Item><Item><Element type="Constant"><AdditionalData><anyType xmlns:q1="http://www.w3.org/2001/XMLSchema" d15p1:type="q1:double" xmlns:d15p1="http://www.w3.org/2001/XMLSchema-instance">{filters.month}</anyType></AdditionalData></Element></Item></ElementCollection></SubElements><AdditionalData Operator="Equal" /></Element></Item></ElementCollection></SubElements><AdditionalData /></Element></Item></ElementCollection></SubElements><AdditionalData Operator="AND" /></Element>')
                    }
                },
                mappingType: 'xml',
                mapping: {
                    workLoad: 'c3',
                    workingDaysWLWthHolidays: 'c4',
                    workingDaysWLCU: 'c5'
                }
            },
            extraParams: {
                viewId: 1709
            },
            url: 'xxx',
            reader: {
                type: 'intuo',
                rootProperty: 'DocumentElement',
                record: 'WEB_x0020_všechny_x0020_časové_x0020_fondy'
            },
            writer: {
                type: 'intuo'
            }
        }
    }
});