/*
 * File: app/view/ClientDetailView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.ClientDetailView', {
    extend: 'Ext.Container',
    alias: 'widget.clientDetailView',

    requires: [
        'Ext.Toolbar',
        'Ext.Label',
        'Ext.Button',
        'Ext.carousel.Carousel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'card',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 50,
                items: [
                    {
                        xtype: 'label',
                        html: '',
                        itemId: 'caruselTitle',
                        margin: 5,
                        width: 100
                    },
                    {
                        xtype: 'label',
                        itemId: 'quickInfo'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 50,
                        text: '+'
                    }
                ]
            },
            {
                xtype: 'carousel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Průběhy<br />péče',
                        itemId: 'clientInfoContainer',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'list',
                                flex: 500,
                                width: 500,
                                itemTpl: [
                                    '{[Ext.Date.format(values.time, \'d. m. Y H:i\')]} {nurse}<br/>',
                                    '{aggreement}'
                                ],
                                store: 'NurseCareStore'
                            },
                            {
                                xtype: 'container',
                                flex: 268,
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'label',
                                        html: 'Délka [min]:'
                                    },
                                    {
                                        xtype: 'label',
                                        itemId: 'nurseCareLength'
                                    },
                                    {
                                        xtype: 'label',
                                        html: 'Popis:'
                                    },
                                    {
                                        xtype: 'label',
                                        itemId: 'nurseCareDescription'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Medikace',
                        items: [
                            {
                                xtype: 'label',
                                html: 'test 2'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});