/*
 * File: app/view/ClientNewMenu.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.ClientNewMenu', {
    extend: 'Ext.Panel',
    alias: 'widget.clientNewMenu',

    config: {
        hideOnMaskTap: true,
        layout: {
            type: 'vbox'
        },
        modal: true,
        items: [
            {
                xtype: 'button',
                'text-align': 'left',
                style: 'border-bottom: 1px solid black; border-radius: 0;',
                ui: 'plain',
                text: '<div style="text-align: left">Průběh péče</div>'
            },
            {
                xtype: 'button',
                style: 'border-bottom: 1px solid black; border-radius: 0;',
                ui: 'plain',
                text: '<div style="text-align: left">Lékařská zpráva</div>'
            },
            {
                xtype: 'button',
                ui: 'plain',
                text: '<div style="text-align: left">Konzultace</div>'
            }
        ]
    }

});