/*
 * File: app/view/LoadingView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.LoadingView', {
    extend: 'Ext.Container',
    alias: 'widget.loadingView',

    config: {
        itemId: 'mycontainer3',
        layout: {
            align: 'center',
            pack: 'center',
            type: 'hbox'
        },
        scrollable: false,
        items: [
            {
                xtype: 'image',
                src: 'touch/resources/themes/images/default/loading.gif'
            },
            {
                xtype: 'label',
                html: 'Pracuji...'
            }
        ]
    }

});