/*
 * File: app/view/LoadingView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.LoadingView', {
    extend: 'Ext.Container',
    alias: 'widget.loadingView',

    requires: [
        'Ext.Img',
        'Ext.Label'
    ],

    config: {
        itemId: 'mycontainer3',
        scrollable: false,
        layout: {
            type: 'hbox',
            align: 'center',
            pack: 'center'
        },
        items: [
            {
                xtype: 'image',
                src: 'touch/resources/themes/images/default/loading.gif'
            },
            {
                xtype: 'label',
                html: 'Pracuji...'
            }
        ]
    }

});