/*
 * File: app/view/LoginView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.LoginView', {
    extend: 'Ext.Container',
    alias: 'widget.loginView',

    config: {
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Přihlášení'
            },
            {
                xtype: 'formpanel',
                id: 'loginForm',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'textfield',
                        margin: 10,
                        minWidth: '',
                        width: '90%',
                        label: 'Přihlašovací jméno',
                        name: 'username'
                    },
                    {
                        xtype: 'passwordfield',
                        margin: 10,
                        width: '90%',
                        label: 'Heslo',
                        name: 'password'
                    },
                    {
                        xtype: 'button',
                        id: 'loginButton',
                        margin: 10,
                        maxWidth: 200,
                        text: 'Přihlásit'
                    }
                ]
            }
        ]
    }

});