/*
 * File: app/view/LoginView.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.LoginView', {
    extend: 'Ext.Container',
    alias: 'widget.loginView',

    requires: [
        'Ext.TitleBar',
        'Ext.form.Panel',
        'Ext.field.Password',
        'Ext.field.Checkbox',
        'Ext.Button'
    ],

    config: {
        layout: 'card',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Přihlášení'
            },
            {
                xtype: 'formpanel',
                id: 'loginForm',
                layout: {
                    type: 'vbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'username',
                        margin: 10,
                        minWidth: '',
                        width: '90%',
                        label: 'Přihlašovací jméno:',
                        name: 'username'
                    },
                    {
                        xtype: 'passwordfield',
                        margin: 10,
                        width: '90%',
                        label: 'Heslo:',
                        name: 'password'
                    },
                    {
                        xtype: 'container',
                        margin: 5,
                        width: '90%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                itemId: 'saveUsername',
                                width: 250,
                                label: 'Zapamatovat jméno?',
                                labelWidth: '70%'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'loginButton',
                                margin: 10,
                                maxWidth: 200,
                                text: 'Přihlásit'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        width: '90%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'saveUsernameHelpButton',
                                style: 'color: blue; text-decoration: underline;',
                                ui: 'plain',
                                text: 'Jak funguje zapamatování jména?'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});