/*
 * File: app/view/NewNurseCareView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.NewNurseCareView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newNurseCareView',

    requires: [
        'Ext.Toolbar',
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.field.Number',
        'Ext.field.TextArea'
    ],

    config: {
        itemId: 'myformpanel2',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top'
            },
            {
                xtype: 'fieldset',
                layout: 'hbox',
                title: 'Datum',
                items: [
                    {
                        xtype: 'datepickerfield',
                        flex: 40,
                        itemId: 'date',
                        label: 'Den',
                        placeHolder: 'mm/dd/yyyy',
                        dateFormat: 'd. m. Y',
                        picker: {
                            height: 400,
                            dayText: 'Den',
                            monthText: 'Měsíc',
                            slotOrder: [
                                'day',
                                'month',
                                'year'
                            ],
                            yearFrom: 2013,
                            yearText: 'Rok',
                            doneButton: 'Hotovo',
                            cancelButton: 'Zrušit'
                        }
                    },
                    {
                        xtype: 'selectfield',
                        flex: 30,
                        itemId: 'hour',
                        label: 'Hod.',
                        displayField: 'value',
                        store: 'Hours'
                    },
                    {
                        xtype: 'selectfield',
                        flex: 30,
                        itemId: 'minute',
                        label: 'Min.',
                        displayField: 'label',
                        store: 'Minutes'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                layout: 'hbox',
                title: 'Trvání',
                items: [
                    {
                        xtype: 'numberfield',
                        flex: 34,
                        itemId: 'workDuration',
                        label: 'Práce'
                    },
                    {
                        xtype: 'numberfield',
                        flex: 33,
                        itemId: 'transportDuration',
                        label: 'Doprava',
                        labelWidth: '40%'
                    },
                    {
                        xtype: 'numberfield',
                        flex: 33,
                        itemId: 'documentationDuration',
                        label: 'Dokumentace',
                        labelWidth: '50%'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                layout: 'hbox',
                title: 'Práce',
                items: [
                    {
                        xtype: 'selectfield',
                        flex: 40,
                        itemId: 'serviceType',
                        label: 'Z.P.',
                        labelWidth: '20%',
                        displayField: 'Value',
                        store: 'ServiceType',
                        valueField: 'ID'
                    },
                    {
                        xtype: 'selectfield',
                        flex: 30,
                        itemId: 'wayOfWorking',
                        label: 'Typ',
                        labelWidth: '25%',
                        displayField: 'Value',
                        store: 'WayOfWorking',
                        valueField: 'ID'
                    },
                    {
                        xtype: 'selectfield',
                        flex: 30,
                        itemId: 'formWork',
                        label: 'Forma',
                        displayField: 'Value',
                        store: 'FormWork',
                        valueField: 'ID'
                    }
                ]
            },
            {
                xtype: 'textfield',
                itemId: 'aggreement',
                margin: 10,
                label: 'Domluva',
                labelWidth: '15%',
                name: 'domluva'
            },
            {
                xtype: 'textareafield',
                itemId: 'description',
                margin: 10,
                label: 'Popis',
                labelWidth: '15%',
                name: 'popis'
            },
            {
                xtype: 'button',
                itemId: 'save',
                margin: 10,
                width: '30%',
                text: 'Uložit'
            }
        ]
    }

});