/*
 * File: app/view/RoleSelectView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.RoleSelectView', {
    extend: 'Ext.Container',
    alias: 'widget.roleSelectView',

    requires: [
        'Ext.TitleBar',
        'Ext.Button'
    ],

    config: {
        layout: {
            type: 'vbox',
            align: 'center',
            pack: 'center'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Vyberte svojí roli'
            },
            {
                xtype: 'button',
                height: 100,
                itemId: 'careRole',
                margin: 10,
                width: 300,
                text: 'Přímá péče'
            },
            {
                xtype: 'button',
                height: 100,
                itemId: 'officeRole',
                margin: 10,
                width: 300,
                text: 'Kancelář'
            }
        ]
    }

});