/*
 * File: app/view/SaveUsernameHelp.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.SaveUsernameHelp', {
    extend: 'Ext.Panel',
    alias: 'widget.saveUsernameHelp',

    config: {
        html: '<div style="padding: 5px">Pokud zaškrtnete tuto volbu, pak se vám po úspěšném přihlášení uloží na tomto zařízení použité přihlašovací jméno. Při příštím příchodu na přihlašovací formulář se pak toto jméno automaticky předvyplňuje.</div><div style="padding: 5px">Pokud chcete zrušit předvyplňování přihlašovacího jména, jednoduše odškrtněte tuto volbu a přihlašovací jméno bude z tohoto zařízení okamžitě vymazáno.</div><div style="padding: 5px">Pro zavření této nápovědy ťukněte kamkoliv mimo tento rámeček.</div>',
        itemId: 'mypanel',
        hideOnMaskTap: true,
        modal: true
    }

});