/*
 * File: app/view/WorkReportsView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.WorkReportsView', {
    extend: 'Ext.Container',
    alias: 'widget.workReportsView',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        layout: {
            type: 'vbox'
        },
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Výkazy práce'
            },
            {
                xtype: 'formpanel',
                height: 161,
                items: [
                    {
                        xtype: 'selectfield',
                        itemId: 'employee',
                        margin: 5,
                        label: 'Zaměstnanec',
                        name: 'employee',
                        displayField: 'comboLabel',
                        store: 'EmployeesStore',
                        usePicker: 'auto',
                        valueField: 'ID'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'timeInterval',
                        margin: 5,
                        label: 'Období',
                        name: 'timeInterval',
                        displayField: 'label',
                        store: 'WorkReportIntervals',
                        valueField: 'id'
                    },
                    {
                        xtype: 'container',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'loadWorkReports',
                                margin: 5,
                                text: 'Načíst výkazy práce'
                            },
                            {
                                xtype: 'button',
                                disabled: true,
                                itemId: 'createWorkReports',
                                margin: 5,
                                text: 'Vytvořit přehled z načtených výkazů'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'list',
                flex: 100,
                emptyText: 'Žádné záznamy',
                itemTpl: [
                    '{label}'
                ],
                store: 'WorkReportsStore'
            }
        ]
    }

});